In [1]:
import numpy as np
from tensorflow import keras 
from keras.datasets import mnist
from keras.layers import Dense
from keras.models import Sequential
from keras.utils import to_categorical

In [2]:
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

In [3]:
print("training images shape: ", train_images.shape)
print("training labels shape: ", train_labels.shape)
print("test images shape: ", test_images.shape)
print("test labels shape: ", test_labels.shape)


training images shape:  (60000, 28, 28)
training labels shape:  (60000,)
test images shape:  (10000, 28, 28)
test labels shape:  (10000,)


In [4]:
train_images = train_images.reshape(-1, 784)
test_images = test_images.reshape(-1, 784)

In [5]:
print("training images shape: ", train_images.shape)
print("training labels shape: ", train_labels.shape)
print("test images shape: ", test_images.shape)
print("test labels shape: ", test_labels.shape)

training images shape:  (60000, 784)
training labels shape:  (60000,)
test images shape:  (10000, 784)
test labels shape:  (10000,)


In [6]:
train_images[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   3,  18,  18,  18,
       126, 136, 175,  26, 166, 255, 247, 127,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,  30,  36,  94, 154, 17

In [7]:
test_images[0]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   

In [8]:
#normalizing data
train_images = train_images / 255.0
test_images = test_images / 255.0

In [9]:
train_images[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [10]:
model = Sequential()
model.add(Dense(64, activation = 'relu', input_shape = (784,)))
model.add(Dense(64, activation = 'relu'))
model.add(Dense(10, activation = 'softmax'))

In [11]:
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [12]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 64)                50240     
_________________________________________________________________
dense_1 (Dense)              (None, 64)                4160      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                650       
Total params: 55,050
Trainable params: 55,050
Non-trainable params: 0
_________________________________________________________________


In [13]:
model.fit(train_images, to_categorical(train_labels), epochs = 10, batch_size = 32)


#observation1: if we dont include batch_size, then for 10 epochs we got train accuracy 93
#observation2: if we include batch_size = 32, then for 10 epochs we got train accuracy 96
#observation3: conclusion is that by including batch size, train accuracy got increased

Epoch 1/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2796 - accuracy: 0.9186
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1289 - accuracy: 0.9613
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0945 - accuracy: 0.9714
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0739 - accuracy: 0.9772
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0592 - accuracy: 0.9812
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0503 - accuracy: 0.9838
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0431 - accuracy: 0.9860
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0374 - accuracy: 0.9878
Epoch 9/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0328 - accuracy: 0.9891
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.027

In [14]:
#evaluate the model

model.evaluate(test_images, to_categorical(test_labels))

313/313 [==============================] - 0s 1ms/step - loss: 0.1056 - accuracy: 0.9730


[0.10556081682443619, 0.9729999899864197]

In [15]:
#save the model to disk

model.save_weights('ffnn_mnist.h5')

In [16]:
#load the model later from disk using
#model.load_weights('ffnn_mnist.h5')



In [17]:
# prediction

# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]
